name: Python on Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  testing:
    uses: ./.github/workflows/action_python_testing.yml

  docker:
    uses: ./.github/workflows/action_docker_publish.yml

#  deploy:
#    runs-on: ubuntu-latest
#    needs: [ testing, docker ]
#    steps:
#      # setup
#      - uses: actions/checkout@v3
#      - name: Set up Python 3.10
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#      # dependency's
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r config/requirements.txt
#      - name: echo
#        run: echo ${{ secrets.DEPLOY_TOKEN }}